In [2]:
print("jshfb")

jshfb


In [3]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [5]:
w1, w2, w3 = 0.3, 0.2, 0.5
weights = [w1, w2, w3]

In [4]:
def crop_yield(region, weights):
    result = 0
    for x,w in zip(region, weights):
            result += x * w
    return result



In [6]:
crop_yield(kanto, weights)


56.8

In [7]:
crop_yield(johto, weights)

76.9

In [8]:
crop_yield(unova, weights)

74.9

In [9]:
import numpy as np

In [14]:
kanto = np.array([73,67,43])
weights = np.array([w1, w2, w3])

In [16]:
print(type(weights))
weights[0]

<class 'numpy.ndarray'>


0.3

In [17]:
np.dot(kanto, weights)

56.8

In [18]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [19]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: user 233 ms, sys: 0 ns, total: 233 ms
Wall time: 231 ms


833332333333500000

In [20]:
#time unique to jupyter
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 4.33 ms, sys: 0 ns, total: 4.33 ms
Wall time: 2.3 ms


833332333333500000

In [24]:
#milti dim array
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

climate_data.shape
weights.dtype

dtype('float64')

In [25]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [26]:
#csv files
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f3d9430e570>)

In [33]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [34]:
print(climate_data)
print(climate_data.shape)

[[25. 76. 99.]
 [39. 65. 70.]
 [59. 45. 77.]
 ...
 [99. 62. 58.]
 [70. 71. 91.]
 [92. 39. 76.]]
(10000, 3)


In [38]:
weights = np.array([0.3, 0.2, 0.5])
yields = np.matmul(climate_data, weights)
yields
yields.shape

(10000,)

In [39]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [40]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:


* Mathematics: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Array manipulation: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`

> **How to find the function you need?** The easiest way to find the right function for a specific operation or use-case is to do a web search. For instance, searching for "How to join numpy arrays" leads to [this tutorial on array concatenation](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/). 

You can find a full list of array functions here: https://numpy.org/doc/stable/reference/routines.html