In [2]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0.post100


In [3]:
print(torch.version.cuda)

None


In [4]:
scalar = torch.tensor(5)
scalar

tensor(5)

In [5]:
scalar.ndim
#dimensions

0

In [6]:
scalar.item()
#get as python int

5

In [7]:
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:


# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim


2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
#random tensor
rt = torch.rand(size=(4,5))
rt

tensor([[0.4405, 0.6049, 0.3972, 0.1471, 0.0955],
        [0.5307, 0.5204, 0.1369, 0.0247, 0.4788],
        [0.3066, 0.2321, 0.4717, 0.3740, 0.5046],
        [0.9500, 0.1019, 0.2315, 0.2507, 0.4140]])

In [17]:
#create random with shape to an image
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [18]:
torch.rand(3,4)

tensor([[0.7347, 0.0127, 0.3237, 0.9995],
        [0.6445, 0.6670, 0.0442, 0.2899],
        [0.6066, 0.1027, 0.3874, 0.2798]])

In [19]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
#range of tensor
a = torch.arange(0,10)
b = torch.arange(start=0, end=1000, step=77)
b

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [22]:
#create tensor like
ten_zeroes = torch.zeros_like(input=a)
ten_zeroes


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:

# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

### Probable errors

Teensor not right datatype

Teensor not right shape

Teensor not right right device

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3772, 0.3123, 0.0096, 0.9153],
        [0.7288, 0.8997, 0.7811, 0.0471],
        [0.1789, 0.0030, 0.3552, 0.2069]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Arithmetic Operations

In [26]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
tensor * 10
# not reassigned
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [28]:
torch.mul(tensor, 10)
torch.add(tensor, 13)


tensor([23, 33, 43])

In [29]:
tensor * tensor

tensor([100, 400, 900])

In [30]:
torch.matmul(tensor, tensor)

tensor(1400)

In [31]:
A_tensor = torch.tensor([[1,2],[3,4],[5,6]])
B_tensor = torch.tensor([[7,8],[9,10],[11,12]])

In [32]:
#transpose
B_tensor.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [33]:
torch.matmul(A_tensor, B_tensor.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [34]:
torch.matmul(A_tensor, B_tensor.T).shape

torch.Size([3, 3])

# find min, max, sun (tensor aggregation)

In [35]:
x = torch.arange(0,100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
torch.min(x)

tensor(0)

In [37]:
torch.max(x)

tensor(90)

In [38]:
#torch.mean(x)
torch.mean(x.type(torch.float32))

tensor(45.)

In [39]:
# positional min and max
# returns index
torch.argmin(x)

tensor(0)

In [40]:
torch.argmax(x)
# 3 hour mark

tensor(9)

In [41]:
#reshaping, stacking, squezing, unsqueezing


`torch.reshape(input, shape)` 	

Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

 `Tensor.view(shape)`	

Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

`torch.stack(tensors, dim=0)`

Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

`torch.squeeze(input)` 

Squeezes input to remove all the dimenions with value 1.

`torch.unsqueeze(input, dim)`

Returns input with a dimension value of 1 added at dim.

`torch.permute(input, dims)` 	

Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [51]:
x = torch.arange(0.,12.)
x, x.shape

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 torch.Size([12]))

In [52]:
x_reshape = x.reshape(2,2,3)
x_reshape,x_reshape.shape
#should be compatible with original dimentions
# meaning, rank multiplication is same

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]]]),
 torch.Size([2, 2, 3]))

In [54]:
z = x.view(4,3)
z, z.shape
# shanres same memory as original, changing z changes x

(tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 torch.Size([4, 3]))

In [56]:
x_stack = torch.stack([x,x,x,x])
x_stack,x_stack.shape

(tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]),
 torch.Size([4, 12]))

In [60]:
x_reshape.squeeze(), x_reshape.squeeze().shape

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]]]),
 torch.Size([2, 2, 3]))

In [63]:
# used in images
x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [68]:
#indexing
# similar to numpy
x = torch.arange(1,10).reshape(1,3,3)
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [70]:
# Torch and Numpy
import numpy as np




In [71]:
# from py to torch
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor
#default datatype is float64
# we get new tensor in memory

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
tensor = torch.ones(7)
np_tsor = tensor.numpy()
tensor, np_tsor
# they dont share memory


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [78]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)


# while not random_tensor_A.equal(random_tensor_B):
#     random_tensor_A = torch.rand(3, 4)
print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")


Tensor A:
tensor([[0.1354, 0.7636, 0.6347, 0.8754],
        [0.9086, 0.2979, 0.5936, 0.7711],
        [0.2635, 0.0531, 0.9851, 0.0045]])

Tensor B:
tensor([[0.6548, 0.5908, 0.5196, 0.2546],
        [0.9680, 0.5925, 0.7120, 0.2565],
        [0.0635, 0.3897, 0.1943, 0.0804]])



In [82]:
RANDOM_SEED = 17
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
random_tensor_C,random_tensor_D

(tensor([[0.4342, 0.5351, 0.8302, 0.1239],
         [0.0293, 0.5494, 0.3825, 0.5463],
         [0.4683, 0.0172, 0.0214, 0.3664]]),
 tensor([[0.4342, 0.5351, 0.8302, 0.1239],
         [0.0293, 0.5494, 0.3825, 0.5463],
         [0.4683, 0.0172, 0.0214, 0.3664]]))

In [83]:
torch.cuda.is_available()

False